### ISSUE TITLE
シェアボックス全画面　全n話の情報がない時の処理追加　他

### ISSUE THREAD

**Issue by bana7-arumi** [Aruminium/d-anime-mylist-frontend#26]

**Comment by bana7-arumi** [comment]
追加機能一覧

- 全n話の情報がない時に”〜放送中〜”と表示させる
- 同じ要素をクリックしたときにレンダーしないようにする
- ヘッダーをクリックするとアニメページに飛ぶようにする
- クリックアニメーション追加
- img -> Imageにする

**Comment by OHMORIYUSUKE** [comment]
- 一話のタイトルがない場合
https://anime.dmkt-sp.jp/animestore/ci_pc?workId=25415

- アニメのマイリストを取得している間は、ローディング画面を表示させるといいかもしれないです。
