### ISSUE TITLE
第1話のタイトルがない場合の処理追加

### ISSUE THREAD

**Issue by bana7-arumi** [Aruminium/d-anime-mylist-frontend#38]

**Comment by OHMORIYUSUKE** [comment]
@Aruminium 
第1話のタイトルがない場合はあり得るのでしょうか？

**Comment by bana7-arumi** [comment]
舞台とかは確認してないですが、劇場版とかは第1話とかないです

<img width="882" alt="スクリーンショット 2022-04-09 17 50 22" src="https://user-images.githubusercontent.com/73931800/162564281-cf04ee2b-3c43-4c45-879c-924ac3676921.png">

**Comment by OHMORIYUSUKE** [comment]
@Aruminium 

盲点でした！バックエンドも修正が必要になりそうです。

１話タイトルがなかったら、`stories`に` `(半角スペース)と同様に、`first`も` `(半角スペース)で返します。よろしくお願いいたします。
