### ISSUE TITLE
ロゴとH1を垂直方向にいい感じに並べる

### ISSUE THREAD

**Issue by OHMORIYUSUKE** [Aruminium/d-anime-mylist-frontend#49]
## 現状

![image](https://user-images.githubusercontent.com/72294945/162566068-31d0d03f-65e0-45db-afd5-7d012d0509a6.png)

文字とロゴを垂直方向にそろえたいです。

**Comment by OHMORIYUSUKE** [comment]
@yud0uhu 

どう思いますか。意見が欲しいです。

**Comment by yud0uhu** [comment]
@OHMORIYUSUKE 
これ、タイトルの文言の長さとか日本語or英語とかで印象が大分変わるのでデザインどうしようかなぁとなやんでたとこでした
垂直にそろえる場合、ロゴが上にのっかるようなイメージですかね？

**Comment by OHMORIYUSUKE** [comment]
@yud0uhu 

横並びでいいと思うのですが、文字とロゴがbottomでそろっているのが気になったのでコメントしました。
