### ISSUE TITLE
埋め込みオプションのトグルの横に{枠線有り},{枠線無し}と表示させる

### ISSUE THREAD

**Issue by yud0uhu** [Aruminium/d-anime-mylist-frontend#58]
https://github.com/Aruminium/d-anime-mylist-frontend/pull/53 より

**Comment by OHMORIYUSUKE** [comment]
## 提案

- コピーしたときのアラートの✓の色について
  - オレンジは警告のような感じがあるので、マイリストページで使用している緑を使用するのはいかがでしょうか。
 - ✓の下の文言を`Paste this code directly into the HTML portion of your site, and you'll be good to go. Need more info? Check out our developer docs.`から、日本語に変更しませんか？`コピーしました`など
 - コピーボタンとiframeの間隔を開けませんか？

**Comment by yud0uhu** [comment]
> コピーしたときのアラートの✓の色について

Alertの警告感同意です。自分もチェックカラーは緑がベターだと思うので統一してみます

> ✓の下の文言をPaste this code directly into the HTML portion of your site, and you'll be good to go. Need more info? Check out our developer docs.から、日本語に変更しませんか？

日本語賛成です。
ただ
`Copyed!`
に
`コピーしました`
だと被ってしまうので、多少長めの説明文がいいかな？とおもってます。
```
このコードをあなたのサイトのHTML部分に直接貼り付けてください。
```
とかどうかな？（直訳感あるけど）

- コピーボタンとiframeの間隔を開けませんか？
調整してみます～
（きもちなんpxくらいとかあればおしえてくれるとうれしい）

**Comment by OHMORIYUSUKE** [comment]
@yud0uhu 
> このコードをあなたのサイトのHTML部分に直接貼り付けてください。

いいと思います！

**Comment by OHMORIYUSUKE** [comment]
> （きもちなんpxくらいとかあればおしえてくれるとうれしい）

`m-3`ぐらいがいいと思いました。(4でもいいかも)
